version: "2"
services:
  zap:
    command: [ zap.sh, -daemon, -host, "0.0.0.0", -port, "8080", -config, api.disablekey=true, -config, api.addrs.addr.name=.*, -config, api.addrs.addr.regex=true ]
    env_file: ##WORKING_DIR##/config.env
    image: owasp/zap2docker-bare
    ports:
     - 8080